directories:
  output: dist-electron
  buildResources: build
appId: com.nexus.chat
productName: Nexus Chat
files:
  - filter:
      - dist/**/*
      - electron/**/*
mac:
  target: dmg
  icon: public/icons/icon.icns
win:
  target: nsis
  icon: public/icons/icon.ico
electronVersion: 28.3.3
